/**
 * Фразы, которые whisper выдумывает на шуме и в тишине.
 *
 * Собраны экспериментально: модель прогоняли на записях без речи и записывали
 * всё, что она выдала. Источник — набор данных
 * sachaarbonel/whisper-hallucinations на Hugging Face, лицензия MIT.
 *
 * Взята узкая часть: длинные фразы — от четырёх слов, а для письменностей без
 * пробелов от восьми знаков, — которые либо встретились на шуме не один раз,
 * либо содержат служебные слова вроде «субтитры», «подпишитесь», «спасибо за
 * просмотр». Список целиком брать нельзя: в начале его по частоте стоят
 * «bye», «you», «thank you» — это обычная речь, и фильтр по ним вырезал бы
 * живой диалог. Отсев по тому же правилу отбрасывает, например, немецкое
 * «es ist eine sehr schöne stadt» — «это очень красивый город».
 *
 * Сравнение идёт с репликой целиком, а не по вхождению: чтобы попасть под
 * правило, реплика должна совпасть с формулой слово в слово.
 */
export const KNOWN_HALLUCINATIONS: ReadonlySet<string> = new Set([
  "a thank you for watching",
  "abone olmayı beğenmeyi ve yorum yapmayı unutmayın",
  "abone olmayı ve videoyu beğenmeyi unutmayın",
  "abone olmayı yorum yapmayı ve beğen butonuna tıklam",
  "abonnez vous à ma chaîne",
  "and subscribe to my channel",
  "bu videoyu beğenmeyi ve kanalımıza abone olmayı unut",
  "críbete al canal gracias",
  "dale like y suscríbete",
  "don t forget to subscribe",
  "ete al canal gracias por ver el video",
  "eu acho que eu vou",
  "gracias por ver el video",
  "gracias por ver el video si te gusto dale like y suscríb",
  "gracias por ver el video si te gusto dale me gusta y sus",
  "gracias por ver el video si te gusto dale un me gusta y",
  "gracias por ver el video si te gusto el video dale me",
  "gracias por ver el video si te gustó dale like y suscr",
  "gracias por ver el video suscríbete al canal",
  "gracias por ver el vídeo",
  "gracias por ver el vídeo suscríbete al canal",
  "gracias por ver este video",
  "grazie per la visione",
  "gusta y suscríbete al canal gracias por ver el video",
  "hallo zusammen und willkommen auf meinem kanal",
  "hello everyone welcome to my channel",
  "hi guys welcome back to my channel",
  "i m not sure if this is the right way to do it but i m not sure if this",
  "inscreva se no canal",
  "kanalıma abone olmayı ve videoyu beğenmeyi unutmayın",
  "kanalıma abone olmayı yorum yapmayı ve beğen butonuna",
  "merci d avoir regardé cette vidéo",
  "merci d avoir regardé cette vidéo abonne toi pour d",
  "merci d avoir regardé cette vidéo merci à bientôt",
  "muchas gracias por ver",
  "n oubliez pas de vous abonner",
  "non dimenticare di iscriverti",
  "não se esqueça de se inscrever",
  "obrigado por assistir se inscreva no canal e ative o sin",
  "please subscribe and like thanks for watching",
  "please subscribe to my channel thank you",
  "se inscreva no canal ative notificações e ative notificações",
  "se inscreva no canal e ative as notificações",
  "se inscreva no canal e ative o sininho",
  "se inscreva no canal e ative o sininho para receber notific",
  "sottotitoli e revisione a cura di qtss",
  "subtitles by the amara org community",
  "suscríbete a mi canal",
  "thank you for watching",
  "thank you for watching please subscribe",
  "thanks for watching please subscribe",
  "welcome to my channel",
  "é isso aí valeu",
  "всем привет и добро пожаловать на мой канал",
  "канал субтитры сделал dimatorzok",
  "на наш канал спасибо",
  "на наш канал спасибо за прос",
  "подписывайтесь на мой канал",
  "подписывайтесь на наш канал",
  "подпишись на канал ставь лайк ж",
  "подпишись на канал ставь лайк и",
  "подпишись на канал субтитры",
  "підписуйтесь на наш канал",
  "редактор субтитров а семкин",
  "редактор субтитров а семкин кор",
  "спасибо за субтитры алексею дуб",
  "ставьте лайки и подписывайтесь",
  "ご視聴ありがとうございました",
  "ご視聴ありがとうございます",
  "チャンネル登録お願いします",
  "字幕提供者 李宗盛",
  "字幕由 amara org 社群提供",
  "字幕由amara org社区提供",
  "感谢收看 欢迎订阅我的频道",
  "由 amara org 社群提供的字幕",
  "見てくれてありがとう",
  "謝謝觀看 下次見",
  "请不吝点赞 订阅 转发 打赏支持明镜与点点栏",
  "구독 부탁드려요",
  "구독과 좋아요 부탁드려요",
  "구독과 좋아요는 사랑입니다",
  "시청해 주셔서 감사합니다",
  "시청해주셔서 감사합니다",
  "시청해주셔서 감사합니다 구독 좋아요 댓글",
  "영상편집 및 자막을 사용하였습니다",
  "오늘도 시청해주셔서 감사합니다",
  "오늘도 영상 봐주셔서 감사합니다 구독과",
  "자막제작 기획 앤디 퀸즈",
  "채널 구독 부탁드립니다",
]);
